### ISSUE TITLE
[feature request] VST3 support

### ISSUE THREAD

**Issue by igggo123** [wolf-plugins/wolf-shaper#107]
I need it, because I could scale the GUI.

**Comment by dromer** [comment]
VST3 is implemented in DPF now (CLAP as well), so you could probably enable this now :)

**Comment by pdesaulniers** [comment]
Yes, VST3 support is currently enabled on the master branch! Now, I just need to create a new release :grin:

**Comment by pdesaulniers** [comment]
VST3 and CLAP binaries are now provided in the latest release!
