### ISSUE TITLE
Native window manager resize when possible (LV2, Jack...)

### ISSUE THREAD

**Issue by pdesaulniers** [wolf-plugins/wolf-shaper#109]
This would allow maximizing the window, resizing it without grabbing the resize handle, etc.

**Comment by herodotas** [comment]
Hello, I accidentelly did resize bigger than my resoliution and cant use resize handle, because I dont see. How I can reset plugin to default settings? Windows 7 x64.

**Comment by pdesaulniers** [comment]
@herodotas On Windows, the window size should be stored in
```
C:\Users\<your user name>\AppData\Local\Temp\wolf-shaper.tmp
```

If you delete this file while the UI is closed, the window should be back to its default size when you reopen it.

I hadn't considered that making the window remember its previous size would cause problems :/ I'll disable this feature in a later release.

**Comment by herodotas** [comment]
Thanks, and I do not think it's plugin problem, it's ,maybe, my fault. But
if this will happen again, I report.

2019-10-08, an, 01:06 Patrick Desaulniers <notifications@github.com> rašė:

**Comment by pdesaulniers** [comment]
@herodotas By the way, this issue has been resolved in the latest version of Wolf Shaper. The plugin does not try to remember its size anymore. Now, to reset the size of the plugin, you just have to close the plugin window and reopen it.

**Comment by pdesaulniers** [comment]
This has been implemented in https://github.com/wolf-plugins/wolf-shaper/pull/147.
