### ISSUE TITLE
Can't press buttons or turn knobs, screen becomes black when right-click menu is activated

### ISSUE THREAD

**Issue by yurivict** [wolf-plugins/wolf-shaper#138]
I recorded the screenshot video:
https://people.freebsd.org/~yuri/wolf-shaper-2021-03-15_19.36.48.mp4

In order to clear black I had to move the window a bit.

wolf-shaper-0.1.8
FreeBSD 12.2

**Comment by pdesaulniers** [comment]
Wow, that looks weird! I think switching to upstream DPF (https://github.com/wolf-plugins/wolf-shaper/issues/132) would solve these issues.

**Comment by pdesaulniers** [comment]
@yurivict This weekend, I will setup FreeBSD and see if I can reproduce the issue.

Which window manager do you use? In the video, are you using the JACK build of the plugin?

**Comment by yurivict** [comment]
I use xfce4. This was the Jack build.

**Comment by pdesaulniers** [comment]
I cannot reproduce the issue using xfce4 on FreeBSD 13.0. However, I did run into some trouble while building the plugin: https://github.com/wolf-plugins/wolf-shaper/pull/140

What is the output of `glxinfo | grep "OpenGL version"` ?

**Comment by pdesaulniers** [comment]
@yurivict I have migrated Wolf Shaper to upstream DPF and disabled the context menu. Can you please check if you can still reproduce the issue on the latest master branch?

**Comment by yurivict** [comment]
The current revision breaks:
```
src/pugl.hpp:34:10: fatal error: 'pugl-upstream/include/pugl/pugl.h' file not found
#include "pugl-upstream/include/pugl/pugl.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by pdesaulniers** [comment]
The 'pugl-upstream' submodule in DPF is probably missing on your machine. It is located in this directory: https://github.com/DISTRHO/DPF/tree/pugl-upstream-v2/dgl/src

**Comment by yurivict** [comment]
It works now. Thanks for fixing it.
