### ISSUE TITLE
[1.0.0] error: use of undeclared identifier 'puglGetNativeView'

### ISSUE THREAD

**Issue by yurivict** [wolf-plugins/wolf-shaper#157]
There is no pugl git submodule.
Build breaks with the latest pugl revision.

FreeBSD 13.1

**Comment by pdesaulniers** [comment]
I just verified the latest source tarball, and the submodule appears to be present at the expected location (`dpf/dgl/src/pugl-upstream`). The submodule is also present if I clone the master branch with `--recursive`

If I look at `dpf/.gitmodules`, I see:

```
[submodule "dgl/src/pugl-upstream"]
	path = dgl/src/pugl-upstream
	url = https://github.com/DISTRHO/pugl.git
```

Can you please double-check your build script? Perhaps there is some sort of path mismatch, as seen in this previous issue? https://github.com/wolf-plugins/wolf-shaper/issues/137

**Comment by yurivict** [comment]
.gitmodules only has 1 entry:
https://github.com/wolf-plugins/wolf-shaper/blob/master/.gitmodules

**Comment by yurivict** [comment]
Ah, I see. It's an embedded submodule...
