### ISSUE TITLE
Interface not update

### ISSUE THREAD

**Issue by rty65tt** [wolf-plugins/wolf-shaper#162]
When set/change "Warp knobs" mode not update interface.
If resize, interface update.

Windows 10.

**Comment by pdesaulniers** [comment]
In which plugin host does this problem occur? In other words, which program do you use to load Wolf Shaper?

Also, does the same issue occur if you try to modify the graph, or is it specific to the warp knobs?

**Comment by rty65tt** [comment]
1. Reaper, Tracktion Waveform, wolf-shaper.exe.
2. Just warp knobs.
When you click the arrow to the right or left of the name field, the mode changes, but the name does not.

**Comment by rty65tt** [comment]
it's work
