### ISSUE TITLE
Virus detected after version v1.0.0

### ISSUE THREAD

**Issue by whatevergeek** [wolf-plugins/wolf-shaper#164]
On Windows, when i try to download from v1.0.0 onwards it keeps failing:
Failed - Virus detected
Please see screenshot.
![image](https://github.com/wolf-plugins/wolf-shaper/assets/7351683/86946e52-e723-43a6-b37f-029dfeb64793)
v0.1.8 was ok though

**Comment by pdesaulniers** [comment]
Thanks for the report!

I see that [VirusTotal](https://www.virustotal.com) flags the v1.0.1 release as containing a Trojan.

This issue appears to affect other DPF-based plugins, such as Dragonfly Reverb: https://github.com/michaelwillis/dragonfly-reverb/issues/154

I believe it is a false positive, but I will look into it nonetheless.

Which browser do you use to download Wolf Shaper? Also, do you have any specific antivirus software installed on your machine? Does it create a detailed log entry whenever a virus is detected?

**Comment by pdesaulniers** [comment]
In the meantime, I've tried recompiling Wolf Shaper with a different toolchain (mingw-w64-gcc 12.2.0-1)

Can you please check if this release also triggers a warning in your antivirus? https://github.com/wolf-plugins/wolf-shaper/releases/download/v1.0.2/wolf-shaper-v1.0.2+20230515144200-windows-x64.zip

**Comment by whatevergeek** [comment]
@pdesaulniers seems to be working now... what changed?
![image](https://github.com/wolf-plugins/wolf-shaper/assets/7351683/1d6e19d3-a943-4e1d-9d52-8d58ce0efe15)
