### ISSUE TITLE
Fix update rate issues in some hosts

### ISSUE THREAD

**Issue by pdesaulniers** [wolf-plugins/wolf-shaper#26]
For example, the UI feels very unresponsive in Ardour.

**Comment by deadray6** [comment]
If i understand it correctly, same in bitwig 1.

**Comment by pdesaulniers** [comment]
Yup, it's very blocky in bitwig as well. 

The rendering in DPF seems bound to the host's refresh rate, so we'd have to put the rendering on its own thread somehow. Haven't looked into it yet. Helm is one plugin that doesn't depend on the refresh rate.

The UI is pretty fluid in jalv (LV2 host) at a refresh rate of 60:
jalv.gtk -r 60 "https://github.com/pdesaulniers/spoonie-waveshaper"

**Comment by pdesaulniers** [comment]
OK, the UI should be smoother now :)

**Comment by pdesaulniers** [comment]
Could you confirm that my fix doesn't make bitwig explode on your computer, just so I can feel confident closing this issue? :)

**Comment by deadray6** [comment]
sure; can try today (in 1 to 6 hours)

**Comment by deadray6** [comment]
works fine

**Comment by pdesaulniers** [comment]
Sweet, closing this.

**Comment by pdesaulniers** [comment]
Unfortunately, that fix caused some users to get a completely black UI.

**Comment by pdesaulniers** [comment]
Let's forget this. AFAIK, running the UI on a separate thread would require some crazy error-prone hacks.
